# Generated by Django 4.2.5 on 2025-01-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessUser',
        ),
    ]
