# Generated by Django 4.2.5 on 2025-01-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_businessuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
